### ISSUE TITLE
CustomParser not working

### ISSUE THREAD

**Issue by TRFFT** [jenkinsci/perfpublisher-plugin#18]
Hello,

I am having trouble using this plugin as I generated what seems to be a valid XML report and am still getting an error.
I'm using Jenkins v2.138.1 in Docker with the Performance Publisher plugin  v8.05.
I generated the report with the following generator : [https://wiki.jenkins.io/download/attachments/42468412/xml-generator.jar?version=1&modificationDate=1270879301000&api=v2](https://wiki.jenkins.io/download/attachments/42468412/xml-generator.jar?version=1&modificationDate=1270879301000&api=v2) that I validated by the following DTD : [https://wiki.jenkins.io/download/attachments/42468412/report.dtd?version=1&modificationDate=1262493971000&api=v2](https://wiki.jenkins.io/download/attachments/42468412/report.dtd?version=1&modificationDate=1262493971000&api=v2).

Here is the report : 
```
<?xml version="1.0" encoding="UTF-8"?>
<report name="GeneratedReport-0" categ="GeneratedReport">
  <start>
    <date format="YYYYMMDD" val="20180917" />
    <time format="HHMMSS" val="230949" />
  </start>
  <test name="/file_0/test_0" executed="yes">
    <description><![CDATA[This is the description of the test number 0 member of the 0 file.]]></description>
    <targets>
      <target threaded="false">C</target>
    </targets>
    <platform name="Plateform_0" remote="unknown" capspool="unknown">
      <os>
        <type><![CDATA[Linux-2.6.26-2-amd64-x86_64-with-glibc2.3.2]]></type>
        <name><![CDATA[Linux]]></name>
        <version><![CDATA[2.6.26-2-amd64]]></version>
        <distribution><![CDATA[Linux-2.6.26-2-amd64-x86_64-with-debian-5.0.3]]></distribution>
      </os>
      <processor arch="x86_64">
        <frequency unit="MHz" cpufreq="2667.000" />
      </processor>
      <hardware><![CDATA[nVidia Corporation GeForce 8500 GT (rev a1)]]></hardware>
      <hardware><![CDATA[nVidia Corporation GT200 [Tesla C1060 / Tesla S1070] (rev a1)]]></hardware>
      <compiler name="ifort" version="11.0 20090131" path="." />
      <environment>{PUT HERE ALL YOUR LIBS AND THE DESCRIPTION OF YOUR TEST ENVIRONMENT}</environment>
    </platform>
    <commandline rank="0" time="20100128-195406.590832" duration="0.599782943726">the_first_command_executed</commandline>
    <commandline rank="1" time="20100128-195406.590832" duration="0.599782943726">the_second_command_executed</commandline>
    <result>
      <success passed="no" state="70" hasTimedOut="true" />
      <compiletime unit="s" mesure="0.11510647989827416" isRelevant="true" />
      <performance unit="GFLOPs" mesure="2.6687218433149074" isRelevant="true" />
      <executiontime unit="s" mesure="1.8753069930254462" isRelevant="false" />
      <errorlog><![CDATA[EXEMPLE OF ERROR LOG]]></errorlog>
      <log name="NameOfLogNumber0"><![CDATA[Here it's another of other log]]></log>
    </result>
  </test>
</report>
```

And the error I get when running the plugin : 
```
Report available at /var/jenkins_home/workspace/pagespeed-metrics-job/perfpublisher-report.xml
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Unknown xml file format
	at hudson.plugins.performance.parsers.ParserDetector.detectXMLFileType(ParserDetector.java:158)
	at hudson.plugins.performance.parsers.ParserDetector.detectXMLFileType(ParserDetector.java:132)
Caused: java.lang.RuntimeException: XML parsing error: 
	at hudson.plugins.performance.parsers.ParserDetector.detectXMLFileType(ParserDetector.java:134)
	at hudson.plugins.performance.parsers.ParserDetector.detect(ParserDetector.java:37)
	at hudson.plugins.performance.parsers.ParserFactory.getParserUsingAntPatternRelativePath(ParserFactory.java:73)
	at hudson.plugins.performance.parsers.ParserFactory.getParserWithRelativePath(ParserFactory.java:45)
	at hudson.plugins.performance.parsers.ParserFactory.getParser(ParserFactory.java:41)
	at hudson.plugins.performance.PerformancePublisher.getParsers(PerformancePublisher.java:327)
	at hudson.plugins.performance.PerformancePublisher.perform(PerformancePublisher.java:378)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Publish Performance test result report' marked build as failure
```

It seems there is no Custom parser as explained in the plugin documentation ([here](https://wiki.jenkins.io/display/JENKINS/PerfPublisher+Plugin#PerfPublisherPlugin-How-togenerateyourreports)).
Did I miss something ?

**Comment by eschava** [comment]
Exception is related to the "performance" not "perfpublisher" plugin
